### ISSUE TITLE
send_recv_from_rpc() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by kristiantorres** [itamarst/dask-memusage#6]
Hi,

I am following the  instructions on the github site. First, I installed dask-memusage with `pip install dask_memusage`. I then create my dask cluster with `cluster = LocalCluster(n_workers=3, threads_per_worker=1); client = Client(cluster)`. When I use `install(client.scheduler, "/path/to/csv")`, i get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/torresba/.pyenv/versions/3.8.4/lib/python3.8/site-packages/dask_memusage.py", line 123, in install
    scheduler.add_plugin(plugin)
TypeError: send_recv_from_rpc() takes 0 positional arguments but 1 was given  
```

Am I doing something wrong here?

P.S: Also, I think there is a typo in the github site. Instead of `from dask_memoryusage import install`, I had to use `from dask_memusage import install`

Thanks

**Comment by kristiantorres** [comment]
Hi...any update on this? Thank you!

**Comment by itamarst** [comment]
Hi, sorry, this must've gotten lost in my email so I never saw it. I will try to fix it.

**Comment by itamarst** [comment]
OK, have reproducer, now to figure out why the unit tests don't catch this.

**Comment by itamarst** [comment]
The problem is a typo in your code: you want `install(cluster.scheduler, "/path/to/csv")`, not `install(client.scheduler, "/path/to/csv")`. I.e. **cluster** not **client**.

**Comment by itamarst** [comment]
Please let me know if this fixes the problem for you, and in general would love to hear how `dask-memusage` works for you. You might also find my other memory-related project useful, a memory profiler to help you figure which specific code is responsible for high memory usage: https://pythonspeed.com/fil
